---
language: python
python: ['3.5']
script: make

sudo: required
services: ['docker']

env:
- DOCKER_COMPOSE_VERSION=1.24.1

before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- sysctl -w vm.max_map_count=262144
- docker-compose down
- docker-compose -f setup.yml up
- docker-compose up -d --build 
