---
language: python
python: ['3.5']
script: make

sudo: required
services: ['docker']

before_install:
- sysctl -w vm.max_map_count=262144
- docker-compose down
- docker-compose -f setup.yml up
- docker-compose up -d
